pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Balachandru-ai/Index_repo.git'
            }
        }

        stage('Show Workspace') {
            steps {
                sh '''
                pwd
                ls -la
                find . -maxdepth 3
                '''
            }
        }

        stage('Install Backend Dependencies') {
            steps {
                sh '''
                cd employee-app/backend

                python3 -m venv venv || true

                . venv/bin/activate

                pip install -r requirements.txt
                '''
            }
        }

        stage('Deploy Frontend') {
            steps {
                sh '''
                sudo cp employee-app/frontend/* /usr/share/nginx/html/

                sudo systemctl restart nginx
                '''
            }
        }

        stage('Restart Backend') {
            steps {
                sh '''
                pkill -f uvicorn || true

                cd employee-app/backend

                nohup venv/bin/python -m uvicorn main:app \
                --host 0.0.0.0 \
                --port 8000 \
                > backend.log 2>&1 &
                '''
            }
        }
    }
}
