pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                url: 'https://github.com/Balachandru-ai/employee-app.git'
            }
        }

        stage('Install Backend Dependencies') {
            steps {
                sh '''
                cd backend
                python3 -m venv venv || true
                . venv/bin/activate
                pip install -r requirements.txt
                '''
            }
        }

        stage('Deploy Frontend') {
            steps {
                sh '''
                sudo cp frontend/* /usr/share/nginx/html/
                sudo systemctl restart nginx
                '''
            }
        }

        stage('Restart Backend') {
            steps {
                sh '''
                pkill -f uvicorn || true

                cd backend

                nohup venv/bin/python -m uvicorn main:app \
                --host 0.0.0.0 \
                --port 8000 \
                > backend.log 2>&1 &
                '''
            }
        }
    }
}
